#数据库配置信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security-oauth2?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useAffectedRows=true
    username: root
    password: 20190101